[package]
name = "mcpatch-client"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mcpatch-shared = { path = "../mcpatch-shared" }
config_template_derive = { path = "../config_template_derive" }
json = { workspace = true }
yaml-rust = "0.4.5"
once_cell = "1.19.0"
async-trait = "0.1.79"
tokio = { workspace = true }
