[package]
name = "mcpatch-client"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mcpatch-shared = { path = "../mcpatch-shared" }
config_template_derive = { path = "../config_template_derive" }
crc = "3.0.1"
json = "0.12.4"
yaml-rust = "0.4.5"
tokio = { version = "1.36.0", features = ["full"] }
once_cell = "1.19.0"
async-trait = "0.1.79"
