[workspace]
members = [
    "config_template_derive",
    "mcpatch-shared",
    "mcpatch-manager", 
    "mcpatch-client"
]
resolver = "2"

[profile.release]
strip = "none"
debug = "full"
overflow-checks = true
