# 过滤规则，用来排除工作空间目录下的一些文件可以有多条
# 当每一条过滤规则都全部检测成功时，该文件才对管理端可见，否则会当这个文件不存在
# 过滤规则使用正则表达式，不支持glob表达式
# 以英文感叹号!打头的规则判定条件会翻转，!本身不会被带进正则中
# 编写规则时可以使用test命令快速调试（用pack目录会很麻烦）
filter-rules = []

# 上传脚本的模板文件
upload-script-template = "upload-template.txt"

# 上传脚本的输出文件
upload-script-output = "upload.txt"