name: Manager build and release

on:
  push:
    tags:
      - "m*"

permissions:
  contents: write
  pages: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargo build
        run: |-
          cargo build --bin mcpatch-manager --release
      
      - name: Append version label
        shell: python
        run: |-
          import os
          import re
          import sys
          import platform

          def get_platform():
              pt = sys.platform
              return pt if pt != 'win32' else 'windows'
          def get_architecture():
              return platform.machine().lower()

          os.mkdir('target/release/upload')
          GIT_TAG = os.environ.get('GITHUB_REF_NAME', ' 0.0.0')[1:]
          suffix = f'{get_platform()}-{get_architecture()}-{GIT_TAG}'

          if sys.platform.startswith('win'):
              os.rename('target/release/mcpatch-manager.exe', f'target/release/upload/mcpatch-manager-{suffix}.exe')
              os.rename('target/release/mcpatch_manager.pdb', f'target/release/upload/mcpatch-manager-{suffix}.pdb')
          elif sys.platform.startswith('linux'):
            os.rename('target/release/mcpatch-manager', f'target/release/upload/mcpatch-manager-{suffix}')
            os.rename('target/release/mcpatch-manager.dwp', f'target/release/upload/mcpatch-manager-{suffix}.dwp')

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/upload/*

