name: Client build and release

on:
  push:
    tags:
      - "c*"

permissions:
  contents: write
  pages: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargo build
        run: |-
          cargo build --bin mcpatch-client --release
      
      - name: Append version label
        shell: python
        run: |-
          import os
          import re

          os.mkdir('target/release/upload')

          GIT_TAG = os.environ.get('GITHUB_REF_NAME', ' 0.0.0')[1:]

          os.rename('target/release/mcpatch-client.exe', f'target/release/upload/mcpatch-client-{GIT_TAG}.exe')
          os.rename('target/release/mcpatch_client.pdb', f'target/release/upload/mcpatch_client_{GIT_TAG}.pdb')

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/upload/*

