name: Manager build and release

on:
  push:
    tags:
      - "m*"

permissions:
  contents: write
  pages: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cargo build
        run: |-
          cargo build --bin mcpatch-manager
      
      - name: Append version label
        shell: python
        run: |-
          import os
          import re
          import sys

          os.mkdir('target/debug/upload')
          GIT_TAG = os.environ.get('GITHUB_REF_NAME', ' 0.0.0')[1:]
          if sys.platform.startswith('win'):
              os.rename('target/debug/mcpatch-manager.exe', f'target/debug/upload/mcpatch-manager-{GIT_TAG}.exe')
              os.rename('target/debug/mcpatch_manager.pdb', f'target/debug/upload/mcpatch_manager_{GIT_TAG}.pdb')
          elif sys.platform.startswith('linux'):
            os.rename('target/debug/mcpatch-manager', f'target/debug/upload/mcpatch-manager-{GIT_TAG}')

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/debug/upload/*

