name: Release Manager

on:
  push:
    tags:
      - "m*"

permissions:
  contents: write
  pages: read

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            rustc-target: x86_64-pc-windows-msvc
          - os: ubuntu-latest
            rustc-target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            rustc-target: x86_64-unknown-linux-musl
    runs-on: ${{ matrix.os }}
    env:
      rust-version: '1.81'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download web pages
        run: |-
          curl -L https://github.com/BalloonUpdate/McPatch2Web/releases/download/${GITHUB_REF_NAME:1}/dist.zip -o dist.zip
          unzip dist.zip
          ls

      # - name: Cargo build
      #   env:
      #     MP_RUSTC_TARGET: ${{ matrix.rustc-target }}
      #   run: |-
      #     rustup update ${{ env.rust-version }} && rustup default ${{ env.rust-version }}
      #     rustup target add ${{ matrix.rustc-target }}
      #     cargo ci manager
      
      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: target/dist/*
      
      # - name: Distribute
      #   uses: bxb100/action-upload@main
      #   with:
      #     provider: webdav
      #     provider_options: |
      #       endpoint=${{ secrets.webdav_endpoint }}
      #       username=${{ secrets.webdav_username }}
      #       password=${{ secrets.webdav_password }}
      #       root=${{ secrets.webdav_root_manager }}
      #     include: 'target/dist/**'
